### ISSUE TITLE
wp config [any command] puts a newline between each line in my wp-config.php files

### ISSUE THREAD

**Issue by michacassola** [wp-cli/config-command#119] opened 2020-12-29 14:37 UTC
## wp config [any command] puts a newline between each line in my wp-config.php files

I install WP-CLI as follows because all WordPress folders are owned by `www-data`:

    sudo wget -qO /usr/local/bin/wp-cli https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    sudo chmod +x /usr/local/bin/wp-cli
    sudo tee /usr/local/bin/wp >/dev/null <<'EOF'
    sudo runuser -u www-data -- wp-cli $@
    EOF
    sudo chmod +x /usr/local/bin/wp

Both wrapper commands `sudo runuser -u www-data -- wp-cli $@` and `sudo -u www-data -- wp-cli $@` do this.
`sudo -u www-data -i -- wp-cli $@` gives me this output: `This account is currently not available.`

The commands I ran so far that put a newline between each line in wp-config.php are:

    wp --path=/var/www/$domain/htdocs config shuffle-salts
    wp --path=/var/www/$domain/htdocs config set CLOUDFLARE_HTTP2_SERVER_PUSH_ACTIVE true

I think it is a bug? Any help will be appreciated! Thanks in advance!

**Comment by danielbachhuber** [comment] 2023-09-29 15:03
Thanks for the report, @michacassola.

This looks like a duplicate of https://github.com/wp-cli/config-command/issues/160. Closing in favor of that issue.

**Closed by danielbachhuber** 2023-09-29 15:03 UTC

**Comment by michacassola** [comment] 2023-09-30 09:41
@danielbachhuber 160 comes after 119. 160 is the duplicate.

**Comment by michacassola** [comment] 2023-09-30 09:46
Also this was posted nearly 3 years ago. I guess I won't be reporting any issues in this project because it seems to be useless!
